"""second

Revision ID: 495e77feada7
Revises: 03f5db6f24dc
Create Date: 2020-04-21 18:10:25.278987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '495e77feada7'
down_revision = '03f5db6f24dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_user_profile', 'real_name')
    op.drop_column('ih_user_profile', 'avatar_url')
    op.drop_column('ih_user_profile', 'id_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_user_profile', sa.Column('id_card', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('ih_user_profile', sa.Column('avatar_url', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('ih_user_profile', sa.Column('real_name', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
