"""user

Revision ID: d3a4aec5d231
Revises: 2899de0ff8e3
Create Date: 2020-04-24 11:05:03.582405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3a4aec5d231'
down_revision = '2899de0ff8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_admin_profile', sa.Column('email', sa.String(length=254), nullable=True))
    op.add_column('ih_admin_profile', sa.Column('name', sa.String(length=32), nullable=False))
    op.drop_index('username', table_name='ih_admin_profile')
    op.create_unique_constraint(None, 'ih_admin_profile', ['email'])
    op.drop_column('ih_admin_profile', 'username')
    op.add_column('ih_user_profile', sa.Column('email', sa.String(length=254), nullable=True))
    op.add_column('ih_user_profile', sa.Column('introduction', sa.TEXT(), nullable=True))
    op.add_column('ih_user_profile', sa.Column('name', sa.String(length=30), nullable=False))
    op.add_column('ih_user_profile', sa.Column('sex', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_ih_user_profile_name'), 'ih_user_profile', ['name'], unique=False)
    op.drop_index('username', table_name='ih_user_profile')
    op.create_unique_constraint(None, 'ih_user_profile', ['email'])
    op.drop_column('ih_user_profile', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_user_profile', sa.Column('username', mysql.VARCHAR(length=32), nullable=False))
    op.drop_constraint(None, 'ih_user_profile', type_='unique')
    op.create_index('username', 'ih_user_profile', ['username'], unique=True)
    op.drop_index(op.f('ix_ih_user_profile_name'), table_name='ih_user_profile')
    op.drop_column('ih_user_profile', 'sex')
    op.drop_column('ih_user_profile', 'name')
    op.drop_column('ih_user_profile', 'introduction')
    op.drop_column('ih_user_profile', 'email')
    op.add_column('ih_admin_profile', sa.Column('username', mysql.VARCHAR(length=32), nullable=False))
    op.drop_constraint(None, 'ih_admin_profile', type_='unique')
    op.create_index('username', 'ih_admin_profile', ['username'], unique=True)
    op.drop_column('ih_admin_profile', 'name')
    op.drop_column('ih_admin_profile', 'email')
    # ### end Alembic commands ###
