"""file

Revision ID: de112ac5d956
Revises: f16adcd6dad9
Create Date: 2020-06-07 15:35:32.104962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de112ac5d956'
down_revision = 'f16adcd6dad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ih_files_profile',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ih_files_profile_file_path'), 'ih_files_profile', ['file_path'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ih_files_profile_file_path'), table_name='ih_files_profile')
    op.drop_table('ih_files_profile')
    # ### end Alembic commands ###
