"""8 

Revision ID: f16adcd6dad9
Revises: b175f44cf9d6
Create Date: 2020-05-09 19:46:41.169473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16adcd6dad9'
down_revision = 'b175f44cf9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ih_paper_profile', ['name'])
    op.add_column('ih_question_profile', sa.Column('score', sa.Integer(), nullable=True))
    op.drop_index('mobile', table_name='ih_user_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('mobile', 'ih_user_profile', ['mobile'], unique=True)
    op.drop_column('ih_question_profile', 'score')
    op.drop_constraint(None, 'ih_paper_profile', type_='unique')
    # ### end Alembic commands ###
